### ISSUE TITLE
Jarql is not able to parse Json starting with array

### ISSUE THREAD

**Issue by DavideAllavena** [jarql/jarql#3]
This works:
```
{"array":[{"name":"alessio"}, {"name":"davide"}]}
```
But not this one:
```
[{"name":"alessio"}, {"name":"davide"}]
```

**Comment by retog** [comment]
I've imlemented an approach where each emenet of the root arrays gets mapped to a blank node of type `jarql:Root`. The advantage of this approach is that potentially the same query can be used if the JSON has an object root if there's only one element and an array if there are multiple. The disavantage is that lhe root array must not directly contain strings, so this `["alessio", "davide"] would not be processable.
